[workspace]
members = [
  "packages/*",
  "contracts/*",
]

[workspace.package]
edition      = "2021"
license      = "BSD-3"
rust-version = "1.66"
version      = "0.1.0"

[profile.release]
codegen-units    = 1
debug            = false
debug-assertions = false
incremental      = false
lto              = true
opt-level        = 3
overflow-checks  = true    # very important, do not turn these off.
panic            = 'abort'
rpath            = false

[workspace.dependencies]
cosmwasm-schema = "1.2"
cosmwasm-std    = { version = "1.2", features = ["ibc3"] }
cw-storage-plus = "1.0"
cw-utils        = "1.0"
cw2             = "1.0"

serde     = { version = "1", default-features = false, features = ["derive"] }
thiserror = "1"

# the sha2 version here is the same as the one used by
# cosmwasm-std. when bumping cosmwasm-std, this should also be
# updated. to find cosmwasm_std's sha function:
# ```cargo tree --package cosmwasm-std```
sha2 = "0.10.6"

covenant-clock-derive = { path = "packages/clock-derive" }
cw-fifo = { path = "packages/cw-fifo" }

covenant-clock = { path = "contracts/clock" }
covenant-clock-tester = { path = "contracts/clock-tester" }
covenant-depositor = { path = "contracts/depositor" }

# dev-dependencies
cw-multi-test   = "0.16"
anyhow          = "1"