[package]
name = "covenant-depositor-derive"
version = "0.0.1"
edition = "2021"
authors = ["benskey bekauz@protonmail.com"]
description = "A package for deriving covenant deposit variants"
license = "BSD-3"


[lib]
proc-macro = true

[dependencies]
proc-macro2       = "1"
quote             = "1"
syn               = "1"
