[package]
name = "covenant-utils"
version = { workspace = true }
edition = { workspace = true }
authors = ["benskey bekauz@protonmail.com"]
description = "A package for common utils for covenants"
license = { workspace = true }


[lib]

[dependencies]
cosmwasm-schema  = { workspace = true }
neutron-sdk      = { workspace = true }
cosmwasm-std     = { workspace = true }
prost            = { workspace = true }
cosmos-sdk-proto = { workspace = true }
cw20             = { workspace = true }
astroport        = { workspace = true }
# polytone-note    = { workspace = true }
# polytone         = { workspace = true }
polytone = "1.0.0"
# polytone-note = "1.0.0"
