[package]
name = "covenant-utils"
version = "0.0.1"
edition = "2021"
authors = ["benskey bekauz@protonmail.com"]
description = "A package for common utils for covenants"
license = "BSD-3"


[lib]

[dependencies]
cosmwasm-schema  = { workspace = true }
neutron-sdk      = { workspace = true }
cosmwasm-std     = { workspace = true, features = ["cosmwasm_1_2"] }
prost            = { workspace = true }
cosmos-sdk-proto = { workspace = true }
cw20             = { workspace = true }
astroport        = { workspace = true }
