[package]
name = "cw-fifo"
version = "0.0.1"
edition = "2021"
authors = ["ekez <ekez@withoutdoing.com>"]
description = "A CosmWasm FIFO queue with nice runtime and no size limits."
license = { workspace = true }

[dependencies]
cosmwasm-std = { workspace = true }
cw-storage-plus = { workspace = true }
serde = { workspace = true }
