[package]
name = "covenant-clock-derive"
version = "0.0.1"
edition = "2021"
authors = ["ekez <ekez@withoutdoing.com>"]
description = "A package for deriving the covenant-clock interface."
license = "BSD-3"


[lib]
proc-macro = true

[dependencies]
proc-macro2       = "1"
quote             = "1"
syn               = "1"
