[package]
name = "stride-depositor"
version = "0.0.1"
edition = "2021"
authors = ["benskey bekauz@protonmail.com"]
description = "Depositor module for stride covenant"
license = { workspace = true }

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true }
cw-storage-plus = { workspace = true }
serde = { workspace = true }
cw2 = { workspace = true }
thiserror = { workspace = true }
cw-multi-test = { workspace = true }