[package]
name = "stride-depositor"
version = "0.0.1"
edition      = "2021"
authors = ["benskey bekauz@protonmail.com"]
description = "Depositor module for stride covenant"
license      = "BSD-3"

exclude = [
  "contract.wasm",
  "hash.txt",
]

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
library = []

[dependencies]
cosmwasm-schema = "1.2.1"
cosmwasm-std    = { version = "1.2.4", features = ["ibc3"] }
cw-storage-plus = "1.0.1"
cw-utils        = "1.0.1"
cw2             = "1.0.1"
serde     = { version = "1.0.145", default-features = false, features = ["derive"] }
thiserror = "1.0.31"
# the sha2 version here is the same as the one used by
# cosmwasm-std. when bumping cosmwasm-std, this should also be
# updated. to find cosmwasm_std's sha function:
# ```cargo tree --package cosmwasm-std```
sha2 = "0.10.6"
neutron-sdk = { git = "https://github.com/neutron-org/neutron-sdk", default-features = false, version = "0.5.0" }
cosmos-sdk-proto = { version = "0.14.0", default-features = false }
protobuf = { version = "3.2.0", features = ["with-bytes"] }
schemars = "0.8.10"
serde-json-wasm = { version = "0.4.1" }
base64 = "0.13.0"
prost = "0.11"
prost-types = "0.11"
bech32 = "0.9.0"

# cosmwasm-schema = { workspace = true }
# cosmwasm-std = { workspace = true }
# cw-storage-plus = { workspace = true }
# serde = { workspace = true }
# cw2 = { workspace = true }
# thiserror = { workspace = true }
# cw-multi-test = { workspace = true }
# neutron-sdk = { workspace = true }
# cosmos-sdk-proto = { workspace = true }
# protobuf = { workspace = true }
# schemars = { workspace = true }
# prost = { workspace = true }
# prost-types = { workspace = true }
# serde-json-wasm = { workspace = true }


# # the sha2 version here is the same as the one used by
# # cosmwasm-std. when bumping cosmwasm-std, this should also be
# # updated. to find cosmwasm_std's sha function:
# # ```cargo tree --package cosmwasm-std```
# sha2 = { workspace = true }

# dev-dependencies
[dev-dependencies]
cw-multi-test   = "0.16.2"
anyhow          = { version = "1.0.51" }
# cw-multi-test   = { workspace = true }
# anyhow          = { workspace = true }
