name: interchaintest

permissions:
  contents: write

on:
    pull_request:
    push:

env:
    GO_VERSION: 1.21

jobs:
  docker:
      name: install docker
      runs-on: self-hosted-ubuntu-22.04
      steps:
        - name: Setup Docker Buildx
          uses: docker/setup-buildx-action@v2

  compile-contracts:
      name: compile wasm contract with workspace-optimizer
      # needs: docker
      runs-on: self-hosted-ubuntu-22.04
      container:
        image: cosmwasm/workspace-optimizer:0.14.0
      steps:
          - name: checkout sources
            uses: actions/checkout@v3

          - name: install nodejs
            run: |
              apk update
              apk add nodejs npm
              apk update
              node -v

          - name: install tar for cache
            run: apk add --no-cache tar

          - name: set up cargo cache
            uses: actions/cache@v3
            with:
                path: |
                    ~/.cargo/registry/bin/
                    ~/.cargo/registry/index/
                    ~/.cargo/registry/cache/
                    ~/.cargo/git/db/
                    target/
                key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

          - name: compile contracts
            timeout-minutes: 40
            run: optimize_workspace.sh .

          - name: test ls
            run: ls
          - name: test pwd
            run: pwd

          - name: upload contracts
            uses: actions/upload-artifact@v3
            with:
              name: contracts
              path: artifacts/

          - name: test ls
            run: ls artifacts/

  swap-covenant:
    needs: compile-contracts
    runs-on: self-hosted-ubuntu-22.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: contracts
          path: artifacts/

      - name: Set up Go  ${{ env.GO_VERSION }}
        uses: actions/setup-go@v4
        with:
          go-version:  ${{ env.GO_VERSION }}

      - name: setup just
        uses: extractions/setup-just@v1

      - name: swap covenant
        run: just swap-covenant


  two-party-pol-covenant:
    needs: compile-contracts
    runs-on: self-hosted-ubuntu-22.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: contracts
          path: artifacts/

      - name: Set up Go  ${{ env.GO_VERSION }}
        uses: actions/setup-go@v4
        with:
          go-version:  ${{ env.GO_VERSION }}

      - name: setup just
        uses: extractions/setup-just@v1

      # - name: move wasms to test directories
      #   run: just mv-contracts

      - name: two party POL covenant
        run: just two-party-pol-covenant
        # run: cd two-party-pol-covenant/tests/interchaintest && go test --timeout 30m
