name: interchaintest

on:
  pull_request:
  push:


env:
  GO_VERSION: 1.21
jobs:
  events:
    runs-on: self-hosted-ubuntu-22.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: Set up Go  ${{ env.GO_VERSION }}
        uses: actions/setup-go@v4
        with:
          go-version:  ${{ env.GO_VERSION }}

      - name: install just
        run: |
          sudo apt-get update -qy
          sudo apt-get install -y just
            
      - name: change directory to swap-covenant
        run: cd swap-covenant/

      - name: interchaintest
        run: |
          cd swap-covenant
          just simtest
