name: interchaintest

on:
    pull_request:
    push:

permissions:
    contents: write
          
env:
    GO_VERSION: 1.21

jobs:
  release:
      runs-on: self-hosted-ubuntu-22.04
      container: cosmwasm/workspace-optimizer:0.14.0
      steps:
          - name: Install Node.js
            run: |
              apk add --no-cache nodejs

          - name: checkout sources  
            uses: actions/checkout@v3
          
        #   - run: apk add --no-cache tar

          - name: set up cargo cache
            uses: actions/cache@v3
            with:
                path: |
                    ~/.cargo/registry
                    ~/.cargo/git
                    target
                key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
  
          - name: compile contracts
            timeout-minutes: 30
            run: optimize_workspace.sh .

          - name: Upload contracts
            uses: actions/upload-artifact@v3
            with:
              name: contracts
              path: artifacts/
      
#   events:
#     runs-on: self-hosted-ubuntu-22.04
#     steps:
#       - name: checkout repository
#         uses: actions/checkout@v3

#       - name: Set up Go  ${{ env.GO_VERSION }}
#         uses: actions/setup-go@v4
#         with:
#           go-version:  ${{ env.GO_VERSION }}

#       - name: setup just
#         uses: extractions/setup-just@v1
        
#       - name: interchaintest
#         run: just swap-covenant